version: '3.8'

services:
  # Проект 1
  service-one:
    build:
      context: ./BlazorApp1 # Путь к папке проекта
      dockerfile: Dockerfile
    ports:
      - "5001:8080" # Внешний порт 5001 ведет на внутренний 8080
    restart: always

  # Проект 2
  service-two:
    build:
      context: ./Data
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    restart: always
  
  service-three:
    build:
      context: ./TgBot
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    restart: always