version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: ./BlazorApp1/Dockerfile
    ports:
      - "5001:8080"
    restart: always

  tgbot:
    build:
      context: .
      dockerfile: ./TgBot/Dockerfile
    restart: always